!config
logging: true
preambles:
  build: |
    % arara: pdflatex
    % arara: biber
    % arara: pdflatex
    % arara: pdflatex
    % arara: texcount: {options:['-inc'], html:yes, output: word_count.html }
    % arara: clean: { extensions: [ aux, log, bcf, blg, mw, out, xml,toc, glo, hd, idx, gz, lof, lot, fls, upa,dep,bbl-SAVE-ERROR] }
  clean: |
    % arara: clean: { extensions: [pdf, aux, bbl, bcf, blg, glg, log, glstex, out, run.xml, synctex.gz, auxlock, lof, lot, toc] }
    % arara: clean: { files: [arara.xml, arara.yaml, arara.log] }
