name: Compile Full Thesis
on: workflow_dispatch

permissions:
  contents: write
  pull-requests: write

jobs:
  draft_release:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.date.outputs.version }}
      body: ${{ steps.release_drafter.outputs.body }}
    steps:
      - name: Get current date
        id: date
        run: |
          VERSION=$(date "+%Y.%m.%d")
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Version set to ${VERSION}"
      - uses: release-drafter/release-drafter@v6
        id: release_drafter
        with:
          tag: ${{ steps.date.outputs.version }}
          name: ${{ steps.date.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  tagged-release:
    name: "Tagged Release"
    needs: draft_release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: xu-cheng/latex-action@v4
        with:
          compiler: arara
          args: "--log"
          root_file: thesis.tex
          texlive_version: 2025

      - name: Rename file full
        run: mv thesis_full.pdf thesis_full-${{ needs.draft_release.outputs.tag_name }}.pdf

      - name: Upload PDF file
        uses: actions/upload-artifact@v5
        with:
          name: PDF
          path: |
           thesis_full-${{ needs.draft_release.outputs.tag_name }}.pdf
           word_count.html
           arara.log

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.draft_release.outputs.tag_name }}
          body: ${{ needs.draft_release.outputs.body }}
          make_latest: true
          files: |
            thesis_full-${{ needs.draft_release.outputs.tag_name }}.pdf
            word_count.html
            arara.log
